//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagonoteCommand.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MagonoteCommand.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   今日の日付からオフセットした日付を取得する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CommandDescriptionGetDateOffsetDays {
            get {
                return ResourceManager.GetString("CommandDescriptionGetDateOffsetDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   今日の日付を取得する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CommandDescriptionGetDateToday {
            get {
                return ResourceManager.GetString("CommandDescriptionGetDateToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MagonoteCommand-かゆいところに手が届く!!孫の手のようなコマンド集- に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CommandDescriptionRoot {
            get {
                return ResourceManager.GetString("CommandDescriptionRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   終了時に何かのキーの押下を必要とする に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CommandOptionEnablePause {
            get {
                return ResourceManager.GetString("CommandOptionEnablePause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   致命的なエラーが発生しました｡
        ///このアプリケーションを終了します｡
        ///エラーの詳細な情報を[FatalErrorInformation.log]に保存しました｡ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageFatalError {
            get {
                return ResourceManager.GetString("MessageFatalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ===重要なお知らせ=== に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageImportantNotice {
            get {
                return ResourceManager.GetString("MessageImportantNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   何かのキーを押下してください｡ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessagePleasePressAnyKey {
            get {
                return ResourceManager.GetString("MessagePleasePressAnyKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コマンドを指定してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessagePleaseSpecifyCommand {
            get {
                return ResourceManager.GetString("MessagePleaseSpecifyCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カレンダーの種類 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OptionDescriptionCalendarType {
            get {
                return ResourceManager.GetString("OptionDescriptionCalendarType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   日付の書式 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OptionDescriptionDateFormat {
            get {
                return ResourceManager.GetString("OptionDescriptionDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   オフセット日数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OptionDescriptionOffsetDays {
            get {
                return ResourceManager.GetString("OptionDescriptionOffsetDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カレンダーの種類は &apos;Gregorian&apos; または &apos;Japanese&apos; のいずれかで指定してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OptionErrorCalendarType {
            get {
                return ResourceManager.GetString("OptionErrorCalendarType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   日付の書式が誤っています｡ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OptionErrorDateFormat {
            get {
                return ResourceManager.GetString("OptionErrorDateFormat", resourceCulture);
            }
        }
    }
}
